### ISSUE TITLE
Missing *.obj in workdir\resources

### ISSUE THREAD

**Issue by ChemistAion** [Cheaterdev/Spectrum#1]
Hi!
Your '.gitignore' seems to be a little bit aggressive for 'workdir\resources'

**Comment by Cheaterdev** [comment]
Hi! 
Never thought that someone would ever try to checkout this project :)
That was autogenerated gitignore, i'll replace it with a proper one.

**Comment by ChemistAion** [comment]
I did... :) and even manage to compile both branches... :) unfortunately not "working" but even this I am happy to look around.
There was also missing "copytexture" header somewhere but I build it up.

**Comment by Cheaterdev** [comment]
There are some autogenerated files. Need to run SIGParser first to generate them.
