### ISSUE TITLE
 Missing "sharpmake" DLLs

### ISSUE THREAD

**Issue by ChemistAion** [Cheaterdev/Spectrum#4]
I have to build latest sharpmake into 'sharpmake' directory since there are missing DLLs.
I think you need at least: 'Sharpmake.dll', 'Sharpmake.Generators.dll' and 'Sharpmake.CommonPlatforms.dll'

Consider adding sharpmake as a git::submodule.

**Comment by Cheaterdev** [comment]
For this step you need to build Sharpmake. It's not automated yet.
Or, you can download my binaries: https://cheater.dev/sharpmake.rar

**Comment by ChemistAion** [comment]
Thanks, I did this already :)
BTW: I switched to sharpmake from CMake in my own engine project a week ago - I love it since!
