### ISSUE TITLE
AssetManager::AssetManager fails on finding "assets"

### ISSUE THREAD

**Issue by ChemistAion** [Cheaterdev/Spectrum#6]
During 'RenderApplication' initialization we cannot find/load assets.
Here, we fails with two "[DEBUG] (...) The system cannot find the path specified." messages.
https://github.com/Cheaterdev/Spectrum/blob/8499a0ccb08b72d5aa863a9adaf34c6327575cad/sources/RenderSystem/Assets/Asset.cpp#L18

Initialization continues after that.

**Comment by Cheaterdev** [comment]
This can happen when there are no assets folder presented in workdir.
If there are no engine assests - i'm loading them from original files(obj,png...) but don't saving them. 
To save them - press "Save" in Assets Explorer tab.

**Comment by ChemistAion** [comment]
Perfect.
