### ISSUE TITLE
PSOHolder::PSOHolder::init_pso fails on PSO::FontRenderClip

### ISSUE THREAD

**Issue by ChemistAion** [Cheaterdev/Spectrum#7]
FYI: I am working on non developement-mode Windows 10 Pro (10.0.18363), I've provided dxil.dll from latest SDK (10.0.19041.0) to sign the shaders.

PSO::FontRender fails, ID3D12Debug enabled for below output:

[INFO] : 5602 PSO:  FontRender
[DEBUG] : 5603 Singleton creating class resource_manager_base<class DX12::vertex_shader,struct D3D::shader_header,class resource_manager<class DX12::vertex_shader,struct D3D::shader_header> >
[DEBUG] : 5627 Singleton creating class Render::layout_id_generator
[DEBUG] : 5651 Singleton creating class resource_manager_base<class DX12::pixel_shader,struct D3D::shader_header,class resource_manager<class DX12::pixel_shader,struct D3D::shader_header> >
[DEBUG] : 5670 Singleton creating class resource_manager_base<class DX12::geometry_shader,struct D3D::shader_header,class resource_manager<class DX12::geometry_shader,struct D3D::shader_header> >
D3D12 WARNING: ID3D12Device::CreateGraphicsPipelineState: The depth stencil unit or pixel shader expects a Depth Stencil View, but the PSO indicates that none will be bound. This is OK, as reads of an unbound Depth Stencil View are defined to return 0; and writes are discarded. It is also possible the developer knows the data will not be used anyway. This is only a problem if the developer actually intended to bind a Depth Stencil View here. [ STATE_CREATION WARNING #680: CREATEGRAPHICSPIPELINESTATE_DEPTHSTENCILVIEW_NOT_SET]
[INFO] : 9474 PSO:  FontRenderClip
D3D12 ERROR: ID3D12Device::CreateGraphicsPipelineState: Vertex Shader - Geometry Shader linkage error: Signatures between stages are incompatible. The input stage requires Semantic/Index (SV_Position,0) as input, but it is not provided by the output stage. [ STATE_CREATION ERROR #666: CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND]
D3D12 ERROR: ID3D12Device::CreateGraphicsPipelineState: Vertex Shader - Geometry Shader linkage error: Signatures between stages are incompatible. The input stage requires Semantic/Index (TEXCOORD,0) as input, but it is not provided by the output stage. [ STATE_CREATION ERROR #666: CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND]
D3D12 ERROR: ID3D12Device::CreateGraphicsPipelineState: Geometry Shader - Pixel Shader linkage error: Signatures between stages are incompatible. The input stage requires Semantic/Index (TC,0) as input, but it is not provided by the output stage. [ STATE_CREATION ERROR #666: CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND]
D3D12 WARNING: ID3D12Device::CreateGraphicsPipelineState: The depth stencil unit or pixel shader expects a Depth Stencil View, but the PSO indicates that none will be bound. This is OK, as reads of an unbound Depth Stencil View are defined to return 0; and writes are discarded. It is also possible the developer knows the data will not be used anyway. This is only a problem if the developer actually intended to bind a Depth Stencil View here. [ STATE_CREATION WARNING #680: CREATEGRAPHICSPIPELINESTATE_DEPTHSTENCILVIEW_NOT_SET]
Exception thrown at 0x00007FF8D7453B29 in spectrum.exe: Microsoft C++ exception: _com_error at memory location 0x000000802B4FB910.
D3D12 ERROR: ID3D12Device::CreateGraphicsPipelineState: Vertex Shader - Geometry Shader linkage error: Signatures between stages are incompatible. The input stage requires Semantic/Index (SV_Position,0) as input, but it is not provided by the output stage. [ STATE_CREATION ERROR #666: CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND]
D3D12 ERROR: ID3D12Device::CreateGraphicsPipelineState: Vertex Shader - Geometry Shader linkage error: Signatures between stages are incompatible. The input stage requires Semantic/Index (TEXCOORD,0) as input, but it is not provided by the output stage. [ STATE_CREATION ERROR #666: CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND]
D3D12 ERROR: ID3D12Device::CreateGraphicsPipelineState: Geometry Shader - Pixel Shader linkage error: Signatures between stages are incompatible. The input stage requires Semantic/Index (TC,0) as input, but it is not provided by the output stage. [ STATE_CREATION ERROR #666: CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND]
D3D12 WARNING: ID3D12Device::CreateGraphicsPipelineState: The depth stencil unit or pixel shader expects a Depth Stencil View, but the PSO indicates that none will be bound. This is OK, as reads of an unbound Depth Stencil View are defined to return 0; and writes are discarded. It is also possible the developer knows the data will not be used anyway. This is only a problem if the developer actually intended to bind a Depth Stencil View here. [ STATE_CREATION WARNING #680: CREATEGRAPHICSPIPELINESTATE_DEPTHSTENCILVIEW_NOT_SET]
Exception thrown at 0x00007FF8D7453B29 in spectrum.exe: Microsoft C++ exception: _com_error at memory location 0x000000802B4FB840.
[ERROR] : 16556  The parameter is incorrect. at:  auto __cdecl DX12::PipelineState::on_change::<lambda_1>::operator ()(void) const
Exception thrown at 0x00007FF7431E3FD2 in spectrum.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

**Comment by Cheaterdev** [comment]
Fixed in c665c65 by removing FontRenderClip - it's unused anyway.
FontRender now disables DS so warning must be fixed.

**Comment by ChemistAion** [comment]
FYI: I have added FontRender warning only to give you a context, I noticed that these (FontRender/FontRenderClip ) are the first not compute pso done in 'init_pso'.
I will continue with your fix later, thank you.
