### ISSUE TITLE
No issue, just some Nsight::Aftermath question...

### ISSUE THREAD

**Issue by ChemistAion** [Cheaterdev/Spectrum#9]
I am happy for you that you catch/fix(WIP-seems to be...) the bug lately i.e.: GPU page fault.
I have integrated Aftermath to my engine also... just "in case" for now, we will see...

My question here is: did you ever use it here (for this particular bug) for your debugging purposes? or you "just" patched pass2pass translation stuff all around and disableed gpu bug-related parts?
Since it is 'orthogonal' to `ID3D12Debug(N)` controllers and `ID3D12InfoQueue` interface, similarly to PIX, i.e.:
you will get `GFSDK_Aftermath_Result_FAIL_D3DDebugLayerNotCompatible` from `GFSDK_Aftermath_DX12_Initialize(...)`.

_For the note: it is not a "request to do something" of any kind, since I am just lurking here at your work/progress/approach as a kind of reference to my own stuff..._

Best regards,
RTJ

**Comment by Cheaterdev** [comment]
Hi! 
My issue was that I was deleting heaps without refcounting by commandlists so heaps were deleted while in use sometimes.
Pass2pass transitions helped me to run async task earlier without waiting the direct queue to make proper transitions and have no depends on that fix.
I did'nt use Aftermath before, but it helped me to find a start point of the issue.

For API debug - D3D API validation helps a lot. 
For render debug - I have a global DebugInfo struct which I can include in any shader and engine will output recorded data via that shaders, so I dont use any PIX, Nsight or other software.

**Comment by ChemistAion** [comment]
...ohh, I see now, thanks for your hints here, I will kept them in mind :)

BTW: regarding the cpu/gpu allocation in general - perhaps I have something interesting for you...
I spent a lot time on this (as everybody else) - especially on "holy grail" of what DX11 (at the driver level) is doing.
Obviously (as a starting point) I investigated this: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator
Lately, I found that talk:  https://www.youtube.com/watch?v=6NWfznwFnMs
He (Adam Sawicki) is a "Developer Technology Engineer" at AMD, and during the talk you could hear (time-to-time) on how DX11 allocates memory... no fancy stuff/techniques, like: big (256MB) ring-buffers (at the DX11-driver/system level no one will notice) etc.
It seems to me that looking for some fancy management: like Diligent is a dead-end...

He (as AMD) lately released DX12 version: https://github.com/GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator.git
This thing looks as he gathered all the "snippets" from his mini-engine (cauldron), here full repo:
https://github.com/GPUOpen-LibrariesAndSDKs/glTFSample.git

I am redesigning my engine to follow these simple patterns (pre allocated memory amount, container techniques etc.)...

**Comment by Cheaterdev** [comment]
For memory usage I switched to placed resources also. Currently don't have many cases - just for frame graph to save much memory and other scene stuff which i'm slowly going to move into framegraph. Memory management is the thing I really want to improve - current state is very "tricky". Currently I'm rewriting this tile mapping part for sparse voxel gi in a more general way.
Also don't want to use any DX12 help libraries (except for font rendering and image loading, it's really painful for now :smile:)

**Comment by ChemistAion** [comment]
Thank you for sharing your insight, very helpful.
I am also doing all the stuff raw as possible by myself... but definitionally not at your level :)

Best regards! RTJ
